### ISSUE TITLE
Creating Order Critical Error

### ISSUE THREAD

**Issue by bigboss97lnt** [weDevsOfficial/dokan#1798]
**Describe the bug**
When creating an admin order it shows the below error:
`There has been a critical error on this website. Please check your site admin email inbox for instructions.`
Debug.log:
```
 PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in /bitnami/wordpress/wp-content/plugins/dokan-lite/includes/Commission.php:276
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/dokan-lite/includes/Order/functions.php(265): WeDevs\Dokan\Commission->get_earning_by_order()
#1 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(310): dokan_sync_insert_order()
#2 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /bitnami/wordpress/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(258): do_action()
#5 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(310): WC_Admin_Meta_Boxes->save_meta_boxes()
#6 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /opt/bitnami/wordpress/wp-includes/post.php(4717): do_action()
#9 /opt/bitnami/wordpress/wp-includes/post.php(4819): wp_insert_post()
#10 /opt/bitnami/wordpress/wp-admin/includes/post.php(426): wp_update_post()
#11 /opt/bitnami/wordpress/wp-admin/post.php(227): edit_post()
#12 {main}
  thrown in /bitnami/wordpress/wp-content/plugins/dokan-lite/includes/Commission.php on line 276
```

**To Reproduce**
1. Go to https://domain.com/wp-admin/post-new.php?post_type=shop_order
2. Change order status to processing
3. Add products
4. Order actions > Create
5. Then it shows the error

**Expected behavior**
Order gets created

**Screenshots**
<img width="760" alt="image" src="https://user-images.githubusercontent.com/64983216/216804666-39284e5e-1593-4126-91c4-fc32db00868c.png">

**Environment:**
 - Dokan Version: 3.7.10
 - Dokan Pro Version: 3.7.13
 - WooCommerce Version: 7.3.0
 - Browser: Chrome Version 109.0.5414.119 (Official Build) (arm64)
 - Current Theme: Flatsome 3.16.4

**Additional context**

**Comment by bigboss97lnt** [comment]
I tested [PR #1800](https://github.com/weDevsOfficial/dokan/pull/1800) and I can confirm problem is solved
